name: build-test

# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

env:
#edit your values here
  ENVIRONMENT_URL: 'https://org27012ef4.crm.dynamics.com/'
  BUILD_ENVIRONMENT_URL: 'https://org18804a32.crm.dynamics.com/'
  CLIENT_ID: '24c10195-f318-492e-afd6-0071aa34a069'
  TENANT_ID: '1557f771-4c8e-4dbd-8b80-dd00a88e833e'

jobs:
  convert-to-managed:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack Solution
      uses: microsoft/powerplatform-actions/pack-solution@0.4.0
      with:
        solution-folder: solutions/miptracker
        solution-file: out/solutions/mipptracker.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@0.4.0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: out/solutions/mipptracker.zip
        force-overwrite: true
        publish-changes: true

# Testing block goes here
    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@0.4.0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: miptracker
        managed: true
        solution-output-file: out/ship/miptracker.zip

    - name: Upload the ready to ship
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/ship/miptracker.zip