name: release-solution-to-build
# prepare for releasing to build:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_run:
    workflows: ["Pack and Build Mip_Tracker"]
    branches: [main]
  types:
      - completed
  workflow_dispatch:
 
env:
#edit your values here
  BUILD_ENVIRONMENT_URL: 'https://org18804a32.crm.dynamics.com/'
  # PRODUCTION_ENVIRONMENT_URL: '<PRODENVIRONMENTURL>'
  CLIENT_ID: '24c10195-f318-492e-afd6-0071aa34a069'
  TENANT_ID: '1557f771-4c8e-4dbd-8b80-dd00a88e833e'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: out/mip_tracker.zip
          solution-folder: solutions/miptracker
          solution-type: 'Unmanaged'
      - uses: actions/upload-artifact@v2
        with:
          name: packed-solution
          path: out/