name: pack-build-test

# pack solution

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to pack'
        required: true
        default: 'miptracker' 

env:
# Your Power Platform SPN
  CLIENT_ID: '24c10195-f318-492e-afd6-0071aa34a069'
  TENANT_ID: '1557f771-4c8e-4dbd-8b80-dd00a88e833e'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: out/${{ github.event.inputs.solution_name }}.zip
          solution-folder: solutions/${{ github.event.inputs.solution_name }}
          solution-type: 'Unmanaged'
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.solution_name }}-packed-solution
          path: out/

